name: Build NGINX Brutal Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository to access the source files.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install required packages.
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget libpcre3-dev zlib1g-dev tar

      # 3. Prepare the module source directory.
      - name: Prepare module source
        run: |
          mkdir -p $HOME/nginx-brutal
          cp "$GITHUB_WORKSPACE/config" "$HOME/nginx-brutal/"
          cp "$GITHUB_WORKSPACE/ngx_http_tcp_brutal_module.c" "$HOME/nginx-brutal/"

      # 4. Download and extract the NGINX source code.
      - name: Download and extract NGINX source code
        run: |
          cd $HOME
          wget http://nginx.org/download/nginx-1.18.0.tar.gz
          tar -xf nginx-1.18.0.tar.gz

      # 5. Configure and compile the module.
      - name: Build the NGINX module
        run: |
          cd $HOME/nginx-1.18.0
          ./configure --with-compat --add-dynamic-module=$HOME/nginx-brutal
          make modules

      # 6. Archive the entire compile directory.
      - name: Archive compiled directory
        run: |
          cd $HOME
          tar czf nginx-compiled.tar.gz nginx-1.18.0

      # 7. Upload the archive as an artifact.
      - name: Upload compiled directory artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-compiled.tar.gz
          path: $HOME/nginx-compiled.tar.gz
